@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.level.levelgen.feature.rootplacers;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;