@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.animation.definitions;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;