@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.chat.contents;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;